@startuml
participant User
participant Scalemail
participant Config
participant HostsFactory
participant Provisioner
participant HostCreator
participant Host
participant AttributesFactory
participant AttributesCatalogue
participant Attributes
participant Attribute

User -> Scalemail: new(ARGS)
activate Scalemail
  Scalemail -> Config: hosts(cfg_file)

  activate Config
    Config -> Config: load_cfg_file(cfg_file)
      Config -> HostsFactory: host(host_hash, options_hash)
      note over Config: for each host node\n in config file
      activate HostsFactory
        HostsFactory -> HostsFactory: process_options
        HostsFactory -> Host: new(attributes_hash, name)
        activate Host
          Host -> AttributesFactory: build(attributes_hash, host_type, driver)
          activate AttributesFactory
            AttributesFactory -> AttributesCatalogue: attribute_records
            activate AttributesCatalogue
              AttributesCatalogue --> AttributesFactory
            deactivate AttributesCatalogue
            note over AttributesFactory: for each attribute_record
            AttributesFactory -> AttributesFactory: attribute_hash
            AttributesFactory -> AttributesFactory: create_attribute(attribute_hash)
            AttributesFactory --> Host
          deactivate AttributesFactory
          Host --> HostsFactory
        deactivate Host
        HostsFactory --> Config
      deactivate HostsFactory
    Config --> Scalemail
  deactivate Config

  Scalemail -> Provisioner: provision(hosts)

  activate Provisioner
    Provisioner -> HostCreator: create(host)
    note over Provisioner: for each host
    activate HostCreator 
      HostCreator -> Host: creation_string
      activate Host
        Host -> Attributes: options_string
        activate Attributes
          note over Attributes: for each option
          Attributes -> Attribute: to_s
          activate Attribute
            Attribute -> Attribute: validate
            Attribute --> Attributes
          deactivate Attribute
          Attributes --> Host
        deactivate Attributes
        Host --> HostCreator
        HostCreator -> Host: sync?
        Host --> HostCreator
      deactivate Host
      HostCreator -> HostCreator: create (sync or async)
      HostCreator --> Provisioner: Future
    deactivate HostCreator
    Provisioner -> Provisioner: wait_for_hosts
    Provisioner --> Scalemail
  deactivate Provisioner
  Scalemail --> User
deactivate Scalemail
@enduml
