options:
  driver: amazonec2
hosts:
  consul:
    host-type: generic
    hosts-amount: 1
    engine-install-url: "https://get.docker.com"
    engine-opts:
      - option1
      - option2
    commands-to-execute:
      - "cd /tmp && touch test.file"
      - "echo $(date) > /tmp/test.file"
      - "cat /tmp/test.file"
    driver:
      amazonec2:
        amazonec2-region: "eu-west-1"
        amazonec2-zone: "a"
        amazonec2-vpc-id: "vpc-23456"
        amazonec2-subnet-id: "subnet-2345"
        amazonec2-security-group: "sg-4665"
        amazonec2-use-private-address: true
        amazonec2-use-private-address-only: true
        amazonec2-instance-type: "t2.micro"
        amazonec2-tags:
          createdBy: 'Docker-Machine'
  swarm-master:
    host-type: swarm-master
    hosts-amount: 1
    engine-install-url: "https://get.docker.com"
    engine-opts:
      - option1
      - option2
    commands-to-execute:
      - "cd /tmp && touch test.file"
      - "echo $(date) > /tmp/test.file"
      - "cat /tmp/test.file"
    swarm-discovery: "consul://$CONSUL_IP:8500"
  swarm-node:
    host-type: swarm-node
    hosts-amount: 3
    engine-install-url: "https://get.docker.com"
    engine-opts:
      - option1
      - option2
    commands-to-execute:
      - "cd /tmp && touch test.file"
      - "echo $(date) > /tmp/test.file"
      - "cat /tmp/test.file"
    swarm-discovery: "consul://$CONSUL_IP:8500"
  nginx:
    host-type: swarm-node
    hosts-amount: 1
    engine-install-url: "https://get.docker.com"
    engine-opts:
      - option1
      - option2
    commands-to-execute:
      - "cd /tmp && touch test.file"
      - "echo $(date) > /tmp/test.file"
      - "cat /tmp/test.file"
    swarm-discovery: "consul://$CONSUL_IP:8500"