options:
  #aws-credentials-profile: default
  hosts-name-prefix: prefix
hosts:
  host:
    driver: amazonec2
    host-type: generic
    hosts-amount: 1
    engine-opts:
      - opt1
      - opt2
    commands-to-execute:
      - ls
    amazonec2-region: region
    amazonec2-zone: zone
    amazonec2-vpc-id: vpc
    amazonec2-subnet-id: subnet
    amazonec2-security-group: sg
    amazonec2-instance-type: it
    amazonec2-ami: ami
